package cn.ce.platform_service.dubbapply.entity;

import java.util.Date;

public class DubboApplyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.pkid
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private Integer pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.id
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.parentId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.appName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.appId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.appCode
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String appcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.unitType
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String unittype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.type
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.packageName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String packagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.className
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.interFaceRealName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String interfacerealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.interFaceName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String interfacename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.interFaceDes
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String interfacedes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.interFaceVersion
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String interfaceversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.fileName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.filePath
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.filetag
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String filetag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.creatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.updatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private Date updattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.creatUserName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String creatusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dubbo_apply.creatUserId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    private String creatuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.pkid
     *
     * @return the value of dubbo_apply.pkid
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.pkid
     *
     * @param pkid the value for dubbo_apply.pkid
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.id
     *
     * @return the value of dubbo_apply.id
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.id
     *
     * @param id the value for dubbo_apply.id
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.parentId
     *
     * @return the value of dubbo_apply.parentId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.parentId
     *
     * @param parentid the value for dubbo_apply.parentId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.appName
     *
     * @return the value of dubbo_apply.appName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.appName
     *
     * @param appname the value for dubbo_apply.appName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.appId
     *
     * @return the value of dubbo_apply.appId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.appId
     *
     * @param appid the value for dubbo_apply.appId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.appCode
     *
     * @return the value of dubbo_apply.appCode
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getAppcode() {
        return appcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.appCode
     *
     * @param appcode the value for dubbo_apply.appCode
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setAppcode(String appcode) {
        this.appcode = appcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.unitType
     *
     * @return the value of dubbo_apply.unitType
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getUnittype() {
        return unittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.unitType
     *
     * @param unittype the value for dubbo_apply.unitType
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setUnittype(String unittype) {
        this.unittype = unittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.type
     *
     * @return the value of dubbo_apply.type
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.type
     *
     * @param type the value for dubbo_apply.type
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.packageName
     *
     * @return the value of dubbo_apply.packageName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.packageName
     *
     * @param packagename the value for dubbo_apply.packageName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setPackagename(String packagename) {
        this.packagename = packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.className
     *
     * @return the value of dubbo_apply.className
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.className
     *
     * @param classname the value for dubbo_apply.className
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.interFaceRealName
     *
     * @return the value of dubbo_apply.interFaceRealName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getInterfacerealname() {
        return interfacerealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.interFaceRealName
     *
     * @param interfacerealname the value for dubbo_apply.interFaceRealName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setInterfacerealname(String interfacerealname) {
        this.interfacerealname = interfacerealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.interFaceName
     *
     * @return the value of dubbo_apply.interFaceName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getInterfacename() {
        return interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.interFaceName
     *
     * @param interfacename the value for dubbo_apply.interFaceName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.interFaceDes
     *
     * @return the value of dubbo_apply.interFaceDes
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getInterfacedes() {
        return interfacedes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.interFaceDes
     *
     * @param interfacedes the value for dubbo_apply.interFaceDes
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setInterfacedes(String interfacedes) {
        this.interfacedes = interfacedes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.interFaceVersion
     *
     * @return the value of dubbo_apply.interFaceVersion
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getInterfaceversion() {
        return interfaceversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.interFaceVersion
     *
     * @param interfaceversion the value for dubbo_apply.interFaceVersion
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setInterfaceversion(String interfaceversion) {
        this.interfaceversion = interfaceversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.fileName
     *
     * @return the value of dubbo_apply.fileName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.fileName
     *
     * @param filename the value for dubbo_apply.fileName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.filePath
     *
     * @return the value of dubbo_apply.filePath
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.filePath
     *
     * @param filepath the value for dubbo_apply.filePath
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.filetag
     *
     * @return the value of dubbo_apply.filetag
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getFiletag() {
        return filetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.filetag
     *
     * @param filetag the value for dubbo_apply.filetag
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setFiletag(String filetag) {
        this.filetag = filetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.creatTime
     *
     * @return the value of dubbo_apply.creatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.creatTime
     *
     * @param creattime the value for dubbo_apply.creatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.updatTime
     *
     * @return the value of dubbo_apply.updatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public Date getUpdattime() {
        return updattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.updatTime
     *
     * @param updattime the value for dubbo_apply.updatTime
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setUpdattime(Date updattime) {
        this.updattime = updattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.creatUserName
     *
     * @return the value of dubbo_apply.creatUserName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getCreatusername() {
        return creatusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.creatUserName
     *
     * @param creatusername the value for dubbo_apply.creatUserName
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setCreatusername(String creatusername) {
        this.creatusername = creatusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dubbo_apply.creatUserId
     *
     * @return the value of dubbo_apply.creatUserId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public String getCreatuserid() {
        return creatuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dubbo_apply.creatUserId
     *
     * @param creatuserid the value for dubbo_apply.creatUserId
     *
     * @mbg.generated Thu Mar 15 09:01:18 CST 2018
     */
    public void setCreatuserid(String creatuserid) {
        this.creatuserid = creatuserid;
    }
}